# Generated by Django 6.0.2 on 2026-02-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('city', models.CharField()),
                ('Age', models.CharField()),
                ('Contact', models.CharField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
