# Generated by Django 6.0.2 on 2026-02-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_delete_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Cpassword',
            field=models.CharField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(default=1234),
            preserve_default=False,
        ),
    ]
