# Generated by Django 6.0.2 on 2026-02-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_cpassword_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='City',
        ),
    ]
